services:
  - type: web
    name: golden-taxi-chiron
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
